image:
  file: .gitpod.Dockerfile

tasks:
  - name: Drupal start
    init: |
      lando start
      lando composer install
      lando drush cim
      lando drush updb
      lando drush cr

vscode:
  extensions:
    - felixfbecker.php-debug
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - marcostazi.VS-code-drupal
    - stylelint.vscode-stylelint
    - tombonnike.vscode-status-bar-format-toggle
    - usernamehw.errorlens
    - whatwedo.twig