stages:
  - build
  - test
  - deploy

.deploy: &deploy
  image: axelerant/platformsh-cli:latest
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
  script:
    - platform project:set-remote ${PLATFORM_PROJECT_ID}
    - platform push --verbose --activate --force --target ${CI_COMMIT_REF_NAME}
    # Explicitly specify the environment as the CLI is not able to figure it out for some reason.
    - PLATFORM_URL=$(platform url --primary --pipe --environment ${CI_COMMIT_REF_NAME})
    - echo "PLATFORM_URL=$PLATFORM_URL" > dotenv
  artifacts:
    reports:
      dotenv: dotenv

drupal_codequality:
  image: hussainweb/drupalqa:php7.4
  stage: test
  script:
    - phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme --ignore=/node_modules/ web/modules/custom
    - phpcs --standard=DrupalPractice --extensions=php,module,inc,install,test,profile,theme --ignore=/node_modules/ web/modules/custom
    - phpmd web/modules/custom/ text phpmd.xml
  tags:
    - docker

drupal_tests:
  image: hussainweb/drupal-base:php7.4
  services:
    - name: registry.axl8.xyz/contrib-tracker/backend/db:latest
      alias: mariadb
  stage: test
  tags:
    - docker
  variables:
    SITE_BASE_URL: 'http://localhost'
    ALLOW_EMPTY_PASSWORD: "yes"

  before_script:
    - ./scripts/gitlab/ci.sh

  script:
    - composer install -o

    # Clearing drush cache and importing configs
    - ./vendor/drush/drush/drush cr
    - ./vendor/drush/drush/drush -y updatedb
    - ./vendor/drush/drush/drush -y config-import

    #  Phpunit execution
    - ./vendor/bin/phpunit --bootstrap=./vendor/weitzman/drupal-test-traits/src/bootstrap-fast.php --configuration ./phpunit.xml --testsuite existing-site

review:
  stage: deploy
  <<: *deploy
  tags:
    - docker
  only:
    - branches
  except:
    - master
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: $PLATFORM_URL
    on_stop: stop_review
    auto_stop_in: 3 days

platformsh:
  stage: deploy
  <<: *deploy
  tags:
    - docker
  only:
    - master
  environment:
    name: production
    url: https://ks.axelerant.com

stop_review:
  stage: deploy
  <<: *deploy
  script:
    - platform environment:delete -y -p $PLATFORM_PROJECT_ID $CI_COMMIT_REF_NAME
  variables:
    GIT_STRATEGY: none
  when: manual
  only:
    - branches
  except:
    - master
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  tags:
    - docker
