stages:
- build
- test
- deploy

drupal_codequality:
  image: hussainweb/drupalqa:latest
  stage: test
  script:
    - phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme --ignore=/node_modules/ web/modules/custom
    - phpcs --standard=DrupalPractice --extensions=php,module,inc,install,test,profile,theme --ignore=/node_modules/ web/modules/custom
    - phpmd web/modules/custom/ text cleancode,codesize,design,naming,unusedcode
  tags:
    - autoscaler

platformsh:
  image: axelerant/platformsh-cli:latest
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  variables:
    PLATFORMSH_CLI_UPDATES_CHECK: '0'
    PF_PARENT_ENV: "master"
    ALLOW_MASTER: '0'
  stage: deploy
  script:
    - platform project:set-remote ${PLATFORM_PROJECT_ID}
    - platform push --verbose --activate --target ${CI_COMMIT_REF_NAME}
  tags:
    - autoscaler
