stages:
- prep
- install
- test
- deploy
- qa

variables:
  DOCKER_DRIVER: overlay
services:
- docker:dind

# Push to platform.
pushtoplatform:
  image: maxc0d3r/platformshcli:axelerant
  variables:
    PLATFORMSH_CLI_UPDATES_CHECK: '0'
    PF_PARENT_ENV: "master"
    ALLOW_MASTER: '0'
  stage: deploy
  script:
    - chmod +x scripts/platform
    - script -q -e -c "./scripts/platform -c deploy"
  tags:
    - autoscaler

# codequality:
#   image: hussainweb/drupal-code-quality:latest
#   stage: test
#   script:
#     - phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme --ignore=/node_modules/  --ignore=/owl/ --ignore=docroot/themes/custom/myomnipod/css/ docroot/modules/custom/ docroot/themes/custom/
#     - phpcs --standard=DrupalPractice --extensions=php,module,inc,install,test,profile,theme --ignore=/node_modules/  --ignore=/owl/ --ignore=docroot/themes/custom/myomnipod/css/ docroot/modules/custom/ docroot/themes/custom/
#     - phpcs --standard=DrupalSecure --extensions=php,module,inc,install,test,profile,theme --ignore=/node_modules/  --ignore=/owl/ --ignore=docroot/themes/custom/myomnipod/css/ docroot/modules/custom/ docroot/themes/custom/
#     - php /usr/local/lib/php-code-quality/vendor/bin/phpmd docroot/modules/custom/,docroot/themes/custom/ text cleancode,codesize,design,naming,unusedcode --exclude /owl/
#     - codespell -S **/node_modules/*,**/myomnipod/bootstrap/* docroot/modules/custom/ docroot/themes/custom/
#     - eslint --ignore-pattern node_modules --ignore-pattern *.min.js docroot/modules/custom docroot/themes/custom/
#     - stylelint docroot/themes/custom/myomnipod/assets/sass/**/*.scss
#   tags:
#     - autoscaler

# executebehat:
#   image: maxc0d3r/platformshcli:axelerant
#   stage: qa
#   script:
#     - chmod +x scripts/platform
#     - script -q -e -c "./scripts/platform -c ssh '/bin/bash scripts/run-tests.sh'"
#   tags:
#     - autoscaler
