stages:
- prep
- install
- test
- deploy
- qa

variables:
  DOCKER_DRIVER: overlay
services:
- docker:dind

# Push to platform.
pushtoplatform:
  image: maxc0d3r/platformshcli:axelerant
  variables:
    PLATFORMSH_CLI_UPDATES_CHECK: '0'
    PF_PARENT_ENV: "master"
    ALLOW_MASTER: '0'
  stage: deploy
  script:
    - chmod +x scripts/platform
    - script -q -e -c "./scripts/platform -c deploy"
  tags:
    - autoscaler

# Job to perform static code analysis.
codequality:
  image: hussainweb/drupal-code-quality:latest
  stage: test
  script:
    - phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme --ignore=/node_modules/ web/modules/custom web/themes/custom/
    - phpcs --standard=DrupalPractice --extensions=php,module,inc,install,test,profile,theme --ignore=/node_modules/ web/modules/custom web/themes/custom/
    - phpcs --standard=DrupalSecure --extensions=php,module,inc,install,test,profile,theme --ignore=/node_modules/ web/modules/custom web/themes/custom/
    - php /usr/local/lib/php-code-quality/vendor/bin/phpmd web/modules/custom/,web/themes/custom/ text cleancode,codesize,design,naming,unusedcode
    - codespell -S **/node_modules/* web/modules/custom/ web/themes/custom/
    - eslint --ignore-pattern node_modules --ignore-pattern *.min.js web/modules/custom web/themes/custom/
    - stylelint web/themes/custom/**/*.scss
  tags:
    - autoscaler

# executebehat:
#   image: maxc0d3r/platformshcli:axelerant
#   stage: qa
#   script:
#     - chmod +x scripts/platform
#     - script -q -e -c "./scripts/platform -c ssh '/bin/bash scripts/run-tests.sh'"
#   tags:
#     - autoscaler
