name: contribtracker
recipe: drupal9

services:
  appserver:
    type: php:8.1
    via: nginx
  cache:
    type: redis:6
  database:
    type: mariadb:10.6
    overrides:
      image: ghcr.io/contrib-tracker/backend-db:main

tooling:
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush
  drupal:
    service: appserver
    cmd: /app/vendor/bin/drupal
  redis-cli:
    service: cache
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit

config:
  php: 8.1
  via: nginx
  webroot: web
  conf:
    php: .lando/php.ini

events:
  post-start:
    - echo "Running post start scripts. Please be patient."
    - cache: redis-cli flushall
    - appserver: composer install && drush cr
