name: contribtracker
recipe: drupal8

# The following additional build step will install the Platform CLI
# in the application container.
services:
  appserver:
    type: php:7.3
    via: nginx
  cache:
    type: redis:5

tooling:
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush
  drupal:
    service: appserver
    cmd: /app/vendor/bin/drupal
  redis-cli:
    service: cache

config:
  php: 7.3
  via: nginx
  webroot: web
  database: mariadb:10.3
  conf:
    php: .lando/php.ini
