name: contribtracker
recipe: drupal8

services:
  appserver:
    type: php:7.4
    via: nginx
  cache:
    type: redis:5
  database:
    type: mariadb:10.5
    overrides:
      image: registry.gitorious.xyz/contrib-tracker/backend/db:latest

tooling:
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush
  drupal:
    service: appserver
    cmd: /app/vendor/bin/drupal
  redis-cli:
    service: cache
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm && echo "Enabling xdebug"
    user: root
  xdebug-off:
    service: appserver
    description: CUSTOM Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm && echo "Disabling xdebug"
    user: root

config:
  php: 7.4
  composer_version: 2.1.3
  via: nginx
  webroot: web
  conf:
    php: .lando/php.ini

events:
  post-start:
    - echo "Running post start scripts. Please be patient."
    - cache: redis-cli flushall
    - appserver: drush cr
