name: contrib-tracker
recipe: drupal8

# The following additional build step will install the Platform CLI
# in the application container.
services:
  appserver:
    build:
      - cd $LANDO_MOUNT && composer install
      - "curl -sS https://platform.sh/cli/installer | php"
  cache:
    type: redis:3.2

# The following entry creates a `lando platform` command that will run
# any Platform CLI command from inside the container if desired.
tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd:
      - /var/www/.platformsh/bin/platform
    options:
      passthrough: true
  redis-cli:
    service: cache

config:
  via: nginx
  webroot: web
  database: mariadb:10.2
