name: contribtracker
recipe: drupal8

# The following additional build step will install the Platform CLI
# in the application container.
services:
  appserver:
    type: php:7.4
    via: nginx
  cache:
    type: redis:5
  database:
    type: mariadb:10.4
    overrides:
      image: registry.gitorious.xyz/contrib-tracker/backend/db:latest

tooling:
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush
  drupal:
    service: appserver
    cmd: /app/vendor/bin/drupal
  redis-cli:
    service: cache
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
config:
  php: 7.4
  via: nginx
  webroot: web
  conf:
    php: .lando/php.ini

events:
  post-start:
    - echo "Running post start scripts. Please be patient."
    - cache: redis-cli flushall
    - appserver: drush cr
