---
# Local Vagrant options.
vagrant_box: geerlingguy/ubuntu1604
vagrant_hostname: contrib.axelerant.dev
vagrant_machine_name: contribtracker
vagrant_ip: 0.0.0.0

# Configure the synced folder.
vagrant_synced_folders:
  - local_path: .
    destination: /var/www/drupal
    type: nfs
    create: true

# Settings for installing a Drupal site if 'install_site:' is 'true'.
drupal_major_version: 8
drupal_domain: "{{ vagrant_hostname }}"
drupal_site_name: "Contrib Tracker"
drupal_install_profile: contrib_tracker
drupal_enable_modules: []
drupal_account_name: ct-admin
drupal_account_pass: admin

# Undo some of the extra-hardened security settings in config.yml.
drupal_db_password: drupal
mysql_root_password: root

php_sendmail_path: "/opt/mailhog/mhsendmail"
installed_extras:
  - adminer
  - drupalconsole
  - drush
  - mailhog
  - pimpmylog
  - xdebug
  - xhprof
