version: 1
snapshot:
  widths:
    - 320
    - 1024
    - 1440
  percy-css: |
    .contextual .trigger { 
      display: none !important;
    }
agent:
  asset-discovery:
    allowed-hostnames:
      - fonts.googleapis.com
