name: CI
on: ["push", "pull_request"]

jobs:
  drupal_codequality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Drupal Code Quality
        uses: hussainweb/drupalqa-action@main
        id: drupalqa
        with:
          checks: |
            phplint: {}
            phpcs:
              standard: phpcs.xml.dist
              ignore: /node_modules/
            phpmd:
              ruleset: phpmd.xml
              suffixes: php
  frontend_codequality:
    runs-on: ubuntu-latest
    container: node:lts
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Frontend Code Quality
        run: |
          cd web/themes/custom/contribtracker
          npm ci
          npm run lint
  drupal_test:
    needs: [drupal_codequality]
    runs-on: ubuntu-latest
    container: hussainweb/drupal-base:php7.4
    env:
      SITE_BASE_URL: "http://localhost"
    services:
      mariadb:
        image: registry.gitorious.xyz/contrib-tracker/backend/db:theme
        env:
          ALLOW_EMPTY_PASSWORD: "yes"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Test
        run: |
          ./.gitlab/ci.sh
          composer install -o --no-progress
          ./vendor/drush/drush/drush cr
          ./vendor/drush/drush/drush deploy -y
          ./vendor/bin/phpunit --testsuite unit
          ./vendor/bin/phpunit --bootstrap=./vendor/weitzman/drupal-test-traits/src/bootstrap-fast.php --configuration ./phpunit.xml --testsuite existing-site
  frontend_vr:
    permissions:
      packages: read
      contents: read
    needs: [frontend_codequality]
    runs-on: ubuntu-latest
    container: skippednote/drupal-cypress:1.0.5
    env:
      SITE_BASE_URL: "http://localhost"
    services:
      mariadb:
        image: registry.gitorious.xyz/contrib-tracker/backend/db:theme
        env:
          ALLOW_EMPTY_PASSWORD: "yes"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup
        run: |
          ./.gitlab/ci.sh
          composer install -o --no-progress
          ./vendor/bin/drush cr
          ./vendor/bin/drush deploy -y
          ./vendor/bin/drush upwd ct-admin "ct-admin"
          cd web/themes/custom/contribtracker
          npm ci --cache $CI_PROJECT_DIR/.npm --prefer-offline
          npm run build
          npm run vr
